version: '3.6'
services:

#  customer:
#    image: quarkus/lojaqueroquero:latest
#    build:
#      context: ./
#      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
#    environment:
#      DATASOURCE_URL: jdbc:postgresql://postgres:5432/lojaqueroquero
#      DATASOURCE_USERNAME: lojaqueroquero
#      DATASOURCE_PASSWORD: strongpassword
#    networks:
#      - microservices
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#      - kafka

  postgres:
    shm_size: 1g
    build: postgres
    environment:
      POSTGRES_USER: lojaqueroquero
      POSTGRES_PASSWORD: strongpassword
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
    name: localhost