CREATE SEQUENCE public.sequence_product INCREMENT 1 START 1 MINVALUE 1;
CREATE SEQUENCE public.sequence_salesman INCREMENT 1 START 1 MINVALUE 1;
CREATE SEQUENCE public.sequence_sale INCREMENT 1 START 1 MINVALUE 1;
CREATE SEQUENCE public.sequence_sale_item INCREMENT 1 START 1 MINVALUE 1;